name: actions
on: 
  push:
    branches:
        - master
  workflow_dispathc:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: execute test script  
        run: ../../test_getgcf.sh
