name: actions
on: 
  push:
    branches:
        - master
  workflow_dispathc:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - run: ../../test_getgcf.sh
